import "./globals.css";
import Nav from "./auth/Nav";
import { Toaster } from "react-hot-toast";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

interface LayoutProps {
  children: React.ReactNode;
}

export const metadata = {
  title: "React Next Postit",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className="bg-gray-200 mx-4 md:mx-48 xl:mx-96 font-roboto">
        <QueryClientProvider client={queryClient}>
          <Toaster />
          {/* https://beta.nextjs.org/docs/configuring/typescript#async-server-component-typescript-error */}
          {/* @ts-expect-error Async Server Component */}
          <Nav />
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
