import "./globals.css";
import Nav from "./auth/Nav";
import {QueryWrapper} from "./components/QueryWrapper";

export const metadata = {
  title: "React Next Postit",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className="bg-gray-200 mx-4 md:mx-48 xl:mx-96 font-roboto">
        <QueryWrapper>
          {/* https://beta.nextjs.org/docs/configuring/typescript#async-server-component-typescript-error */}
          {/* @ts-expect-error Async Server Component */}
          <Nav />
          {children}
        </QueryWrapper>
      </body>
    </html>
  );
}
